# Generated by Django 5.1.4 on 2024-12-09 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.jobpostcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='days_per_week',
            field=models.PositiveIntegerField(verbose_name='Number days'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='hours_per_day',
            field=models.CharField(max_length=20, verbose_name='Daily hours'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='jobpostcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
