# Generated by Django 5.1.4 on 2024-12-11 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('posts', '0002_alter_jobpost_category_alter_jobpost_days_per_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingPostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='HousingPostImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='housing_posts/gallery/', verbose_name='Image')),
            ],
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='region',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='days_per_week',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='hours_per_day',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Company name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], default=1, max_length=10, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.CharField(max_length=255, verbose_name='Salary'),
        ),
        migrations.CreateModel(
            name='HousingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('short_description', models.TextField(max_length=2000, verbose_name='Short description')),
                ('main_image', models.ImageField(upload_to='housing_posts/main_images/', verbose_name='Main image')),
                ('type', models.CharField(choices=[('vip', 'VIP'), ('super_vip', 'Super VIP'), ('premium', 'Premium')], max_length=10, verbose_name='Type')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.region', verbose_name='Region')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.housingpostcategory', verbose_name='Category')),
            ],
        ),
    ]
