# Generated by Django 5.1.4 on 2024-12-14 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housingpost',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AddField(
            model_name='housingpost',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
