# Generated by Django 5.1.4 on 2024-12-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_housingpostcategory_housingpostimagegallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingpost',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Is draft'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Is draft'),
        ),
    ]
