# Generated by Django 5.1.4 on 2024-12-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_housingpost_options_alter_jobpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingpost',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Price'),
        ),
    ]
