# Generated by Django 5.1.4 on 2024-12-12 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_housingpost_is_draft_jobpost_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingpostimagegallery',
            name='housing_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.housingpost', verbose_name='Housing Post'),
            preserve_default=False,
        ),
    ]
