# Generated by Django 5.1.4 on 2024-12-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_housingpostimagegallery_housing_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingpost',
            name='type',
            field=models.CharField(choices=[('for_rent', 'For rent'), ('for_business', 'For business')], max_length=255, verbose_name='Type'),
        ),
    ]
