# Generated by Django 5.1.4 on 2024-12-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_housingpost_author_jobpost_author'),
        ('posts', '0007_housingpost_slug_housingpostcategory_slug_and_more'),
    ]

    operations = [
    ]
